config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :friendships
resources :messages
resources :statuses

    root to: "users#index"
  end

  get 'users/index'
  get 'users/show'

  devise_for :users
  resources :statuses do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "statuses#index"

  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/controllers/admin/statuses_controller.rb
module Admin
  class StatusesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Status.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Status.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @messages = Message.all
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.build
  end

  # GET /statuses/1/edit
  def edit
    authorize! :update, @status
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.build(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    authorize! :update, @status
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    authorize! :destroy, @status
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>
    </div>
  <% end %>
  <%= f.input :name, label: "Title Your Status" %>
  <%= f.input :content, label: "What's Happening?" %>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/statuses/_index.html.erb
<div class="row bootstrap snippets">
    <div class="col-md-6 col-xs-12 col-md-offset-3">
      <div class="panel" id="messge">
        <div class="panel-body">
          <ul class="list-group list-group-full">
            <!-- <li class="list-group-item">
              <div class="media">
                <div class="media-left">
                  <span class="avatar avatar-online">
                    <img src="http://bootdey.com/img/Content/avatar/avatar1.png" alt="">
                    <i></i>
                  </span>
                </div>
                <div class="media-body">
                  <h5 class="list-group-item-heading">
                    <small class="pull-right">3 days ago</small>
                    Herman Beck
                  </h5>
                  <p class="list-group-item-text">Cogitemus tempora tibique probabo...</p>
                </div>
              </div>
            </li> -->
          </ul>
        </div>
      </div>
    </div>
</div>

app/views/statuses/_show.html.erb
<div class="container bootstrap snippet">
  <div class="row">

  </div>
</div>

app/views/statuses/_status.html.erb
<%= link_to 'New Status', new_status_path, class: "btn btn-success btn-xs" %>

<%= render "statuses/index" %>
<% @statuses.each do |status| %>
<div class="status">
  <li class="list-group-item">
    <div class="media">
      <div class="media-left">
        <span class="avatar avatar-online">
          <%= image_tag status.user.image.url(:thumb), class: "img-bordered", size: "100x100" %>
        </span>
    </div>
      <div class="media-body">
        <h5 class="list-group-item-heading">
          <small class="pull-right">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %><br />
            <br>
            <%= link_to status do %>
              This Status has
              <%= status.messages.count %>
              <%= "message".pluralize(status.messages.count) %>
            <% end %>
          </small>
          <strong><%= status.name %></strong>
        </h5>
        <p class="list-group-item-text">
          <%= status.content %>
        </p>
        <span class="admin">
          <% if can? :update, status %>
            <%= link_to 'Edit', edit_status_path(status), class: "btn btn-info btn-xs" %>
          <% end %>
          <% if can? :destroy, status%>
            <%= link_to 'Destroy', status, method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-danger btn-xs" %>
          <% end %>
        </span>
      </div>
    </div>
  </li>
</div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<% unless current_user %>
  <div class="jumbotron">
    <h1>Welcome To Socialville</h1>
    <p>Best place to hang!</p>
    <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg"  %></p>
  </div>
<% end %>

<div class="page-header">
  <h1>Socialville User Statuses</h1>
</div>

<%= render "statuses/status" %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<br>

<%= link_to 'Back', statuses_path, class: "btn btn-link" %>

app/views/statuses/show.html.erb
<span class="admin"> <%= link_to 'Edit', edit_status_path(@status), class: "btn btn-link" %> </span>

<div class="post-list">
  <div class="row">
    <div class="col-sm-2">
      <div class="picture">
        <%= image_tag @status.user.image.url(:thumb), class: "img-rounded", size: "150x150" %>
      </div>
    </div>
    <div class="col-sm-8">
      <h4>
        <label class="label label-primary"><%= @status.user.username %></label>
      </h4>
      <h5>
        <i class="fa fa-calendar"></i>
        <%= time_ago_in_words(@status.created_at) + " ago" %>
      </h5>
      <p class="description"><%= @status.content %>
        <div id="messages">
          <%= render @status.messages %>
        </div>
        <br>
        <%= simple_form_for [@status, Message.new ] do |message| %>
          <%= message.input :content,
                            autofocus: true,
                            placeholder: "Enter Your Message",
                            label: false %>
          <%= message.submit "Send",
                             class: "btn btn-primary" %>
        <% end %>
      </p>
    </div>
    <div class="col-sm-2" data-no-turbolink="">
      <%= link_to " Back", statuses_path, class: "btn btn-default btn-download btn-round pull-right makeLoading fa fa-share" %>
    </div>
  </div>
</div>