config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :friendships
resources :messages
resources :statuses

    root to: "users#index"
  end

  get 'users/index'
  get 'users/show'

  devise_for :users
  resources :statuses do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "statuses#index"

  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/views/layouts/navigation/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Socialville", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render "layouts/navigation/navleft" %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%= render "layouts/navigation/navright" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/navigation/_navleft.html.erb
<li><%= link_to "Statuses", statuses_path if current_user %></li>
<% if current_user %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
    aria-haspopup="true" aria-expanded="false">Profiles/Friends <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to "Everyone", users_path,
        class: "#{'active' unless params[:people]}" %>
      </li>

      <li>
        <%= link_to "Friends", users_path(people: "friends"),
        class: "#{'active' if params[:people] == 'friends'}" %>
      </li>

      <li>
        <%= link_to "Requests", users_path(people: "requests"),
        class: "#{'active' if params[:people] == 'requests'}" %>
      </li>

      <li>
        <%= link_to "Pending", users_path(people: "pending"),
        class: "#{'active' if params[:people] == 'pending'}" %>
      </li>

    </ul>
  </li>
<% end %>

app/views/layouts/navigation/_navright.html.erb
<% unless current_user %>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <li><%= link_to "Sign In", new_user_session_path %></li>
<% end %>
<li><%= link_to "My Profile", user_path(current_user.username) if current_user %></li>
<% if current_user %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle"
    data-toggle="dropdown" role="button" aria-haspopup="true"
    aria-expanded="false">Dropdown <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
      <li role="separator" class="divider"></li>
      <li>
        <%= link_to "End my session",
                    destroy_user_session_path,
                    method: :delete %>
      </li>
    </ul>
  </li>
<% end %>